# Config keys match the `flag` tag value
# When a field doesn't have a `flag` tag, the config key is the struct field name
# Nested structs can be configured using either dot-notation (database.maxconns: 3) or nested maps (database: { maxconns: 3 }), as long as the keys match the struct field names. If a nested field has a flag tag, it can only be configured using its value in the config (e.g., db-url: "...").
srv:
  host: "production-server"
  port: 8443
  apikey: "secret-api-key"
  log-level: "debug"
  log-file: /var/log/mysrv.log
  db-url: postgres://user:pass@localhost/mydb
  database:
    maxconns: 3